### ISSUE TITLE
Use attachment_url from Twitter API

### ISSUE THREAD

**Issue by viniciuskneves** [viniciuskneves/berlin_en_news#11]
Currently the link is part of the body (tweet). We could use the attachment_url to do so. It might also solve this issue #5 

Reference: https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

**Comment by leonardopavanrocha** [comment]
From the documentation above: `Arbitrary, non-Twitter URLs must remain in the status text. URLs passed to the attachment_url parameter not matching either a Tweet permalink or Direct Message deep link will fail at Tweet creation and cause an exception.` Hence, it makes sense to leave the attachment_url in the status (body).

**Comment by viniciuskneves** [comment]
Uhhh, nice catch. I just read `attachment_url` and thought it could be useful! Thanks for double checking =]
